# Generated by Django 5.0 on 2023-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='171680627640', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
